server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    virtual-host: ${SPRING_RABBITMQ_VIRTUAL_HOST:/}
    username: ${SPRING_RABBITMQ_USERNAME:yihen}
    password: ${SPRING_RABBITMQ_PASSWORD:yihen0214}
    listener:
      simple:
        prefetch: 1 # 每次只能获取一条消息，处理完成才能获取下一个消息。解决消息堆积问题
  elasticsearch:
    uris: ${SPRING_ELASTICSEARCH_URIS:http://localhost:9200}
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:${SPRING_REDIS_HOST:localhost}}
      port: ${SPRING_DATA_REDIS_PORT:${SPRING_REDIS_PORT:6379}}
      password: ${SPRING_DATA_REDIS_PASSWORD:${SPRING_REDIS_PASSWORD:}}
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 50MB
  codec :
      max-in-memory-size: 5242880
  jackson:
    # 全局配置时间格式
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource: # mysql数据库配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/YihenDrama?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2b8}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:yihen0214}

logging:
  level:
    org.springframework.web.reactive.function.client.WebClient: DEBUG

# minio配置
minio:
  access-key: ${MINIO_ACCESS_KEY:minioadmin}
  end-point: ${MINIO_END_POINT:http://127.0.0.1:9000}
  secret-key: ${MINIO_SECRET_KEY:minioadmin}

qdrant:
  host: localhost
  port: 6334
  collection-name: novel_content
  dimension: 384
  max-segmentSize-in-tokens: 100
  max-overlap-size-in-tokens: 30
  max-result: 5
  min-score: 0.8

#用于打印框架生成的sql语句，便于调试
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    auto-mapping-behavior: full # 深层次映射
  global-config:
    db-config:
      logic-delete-field: isDeleted #逻辑删除字段
      logic-delete-value: 1
      logic-not-delete-value: 0
